
version: 0.2
env:
  variables:
     PATH: "/root/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/codebuild/user/bin"
phases:
  install:
    runtime-versions:
    commands:
      - apt-get update -y
      - apt-get install -y build-essential clang llvm-dev libclang-dev
      - curl -sSf https://sh.rustup.rs | sh -s -- -y --profile minimal
      - source $HOME/.cargo/env
  build:
    commands:
      - cargo build --release
      # binary name must be "bootstrap" for Lambda custom runtime
      - mv target/release/hellow bootstrap
      - strip --strip-all bootstrap
      - size bootstrap
      - ldd bootstrap
artifacts:
  files:
    - bootstrap
