application:
  host: 127.0.0.1
  base_url: "http://127.0.0.1"
database:
  require_ssl: false
cognito:
  region: "CHANGE_ME"
  user_pool_id: "CHANGE_ME"
  user_pool_client_id: "CHANGE_ME"
  test_user:
    username: "testuser@example.com"
    password: "Password123!"